### ISSUE TITLE
Chinese naming support

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomWarps#1]
When I used the /warps add command, I found that I could only set the name of the teleport I wanted to set to English. Could you add support for Chinese naming for this mod?

**Comment by Pau1am** [comment]
The latest discovery, I found that by adding ' ' to the command to add Chinese named warp. For example as shown below:
![image](https://user-images.githubusercontent.com/41251296/188385210-4a1bcf6d-171c-418d-9101-5ccddd01d317.png)

The warp can be created successfully, so is there a way to create a Chinese-named warp with the ' ' symbol removed?

**Comment by CodedSakura** [comment]
from what i gather, the warp should be added with the quotes automatically removed:
![image](https://user-images.githubusercontent.com/23125996/188387934-10d0e8bd-6eb6-49e7-9171-a4f2cd2ea9b8.png)
