### ISSUE TITLE
Automatically added Warp Commands (/<warp name>) Cause Conflicting Behavior with Existing Commands

### ISSUE THREAD

**Issue by Bloo-dev** [BlossomMods/BlossomWarps#10]
Global warps add themselves as commands of the format `/<warp name>`. This causes issues when a warp is named the same as an **existing** (vanilla or plugin), as it overwrites said command.

## How to Recreate
1. Create a global warp named `/help`
2. Restart the server
3. Type `/help` in chat
4. Notice how no helptext is shown, instead the player is warped

Importantly, permission management mods do not know about the warp command having overwritten the help command. As a result, anyone with permission to run `/help` can now warp to `help`.

## Solutions
Whilst one can argue
> Just don't create warps named after other commands! ):<

I vow against that sentiment. With servers often running long lists of mods there is huge potential for conflict when a command is just named `/<something the player thinks makes sense as a name of a location>`. This makes it easy for users to accidentally run into this scenario, possibly not even noticing until a player/user abuses it.

The shorthand `/<warp name>` should either **be removed completely or there should be a setting** to stop those shorthands from being created.

**Comment by CodedSakura** [comment]
you can disable the permission to add global warps (shorthands) by setting the permission `blossom.warps.add.global` to false. does this achieve your goal?

**Comment by Bloo-dev** [comment]
I might have misunderstood what _global_ means in the context of warps. Does _global_ simply mean that a shorthand command will be created (e.g.` /<warp name>`)?
I.e. a _global_ warp is the same as a normal warp, however, a shorthand command is registered on server startup?

**Comment by CodedSakura** [comment]
yeah, that is how it works

**Comment by Bloo-dev** [comment]
I see, my bad then! Thanks for maintaining this, I will close the issue!
