### ISSUE TITLE
The warps list command is invalid

### ISSUE THREAD

**Issue by Pau1am** [BlossomMods/BlossomWarps#2]
The mod doesn't give me any hints when I use the commands /warps list minecraft:overworld and /warps list minecraft:the_end. But the command /warps list minecraft:the_nether works.

**Comment by CodedSakura** [comment]
is this still an issue? i can't seem to reproduce this with 2.0.2/2.0.3

**Comment by Pau1am** [comment]
Yes, I can still reproduce this with 2.0.3 in my server.
I can post a video at a later time showing this problem.

**Comment by CodedSakura** [comment]
could you also provide a list of the other mods you're using?

**Comment by Pau1am** [comment]
https://youtu.be/AMFP36sHCBc

In the latest version of the mod, all the warps list commands do not work, but in fact I have set up multiple warps on my server, such as the warp centre shown in the video.

Mod list is as follows:
![image](https://user-images.githubusercontent.com/41251296/187136610-af90b9c4-b6d1-43ba-8b4a-eb50f2b0043b.png)

**Comment by Pau1am** [comment]
In addition, after testing, when I use this command in the server console, it will cause the server to forcibly crash and issue the following error:
![image](https://user-images.githubusercontent.com/41251296/187137282-44a51050-fee3-4888-b058-f7e45b3695ad.png)

[crash-2022-08-29_14.29.13-server.txt](https://github.com/BlossomMods/BlossomWarps/files/9442047/crash-2022-08-29_14.29.13-server.txt)

**Comment by CodedSakura** [comment]
alright, thanks for the info, i'll try to look into this whenever i have some spare time

**Comment by Pau1am** [comment]
After testing, the mod that caused the problem is carpet tis addition. When I delete this mod, the warps list command can take effect normally. This is the open source project for this mod: https://github.com/TISUnion/Carpet-TIS-Addition

**Comment by Pau1am** [comment]
In addition, during this process, I found a new bug in the warps list command. After I deleted the carpet tis addition, the warp list command can be used normally, but the displayed content seems to be wrong.
![image](https://user-images.githubusercontent.com/41251296/187144956-e36c9bdf-65e9-495e-9cc5-ef329797f836.png)
![image](https://user-images.githubusercontent.com/41251296/187145031-8ba2c46c-1b67-4c43-bc39-7939af624bb4.png)

**Comment by CodedSakura** [comment]
looking at both StackOverflowErrors, it seems they both have to do with TranslatableText parsing, or at least some kind of text building. that means either i'm doing something some mod doesn't like, or some mod is breaking server-translations-api, or something along those lines. curently i have absolutely no idea what could be causing these errors

**Comment by BackWheel** [comment]
I tried to delete all the extra mods and only keep the BlossomMod, the above problem still occurs.
![image](https://user-images.githubusercontent.com/41251296/188313554-7cab4e7c-ed69-4e6d-a4a5-439e3d355f15.png)

**Comment by Pau1am** [comment]
After further testing, I removed all redundant mods, except for the following mods:
![image](https://user-images.githubusercontent.com/41251296/188313817-f9b64883-9163-4a1e-8ef6-1cb0be2ede6c.png)
But the problem still exists
![image](https://user-images.githubusercontent.com/41251296/188313836-14c35b0b-b324-48e6-b6ea-f0a827722114.png)

**Comment by CodedSakura** [comment]
can you reproduce this error in a new world? or only in that specific one?

**Comment by Pau1am** [comment]
I seem to have discovered some patterns that are causing the problem. First, the problem should be in the BlossomWarps.json file, when I delete and reload a new BlossomWarps.json file and create the first warp in the server's overworld dimension, everything works fine. However, when I enter the second dimension the_end and create a second warp, the problem occurs when I enter the /warps command.
![image](https://user-images.githubusercontent.com/41251296/188314711-a415639d-cc3a-499e-87d9-c961183d5202.png)

**Comment by Pau1am** [comment]
I think I can draw certain conclusions. First of all, the problem is caused by BlossomMod and not by other mods. Secondly, this bug can be reproduced. After my test, it only needs to create 2 warps in one archive to cause the above problem. This is not a single case.

**Comment by CodedSakura** [comment]
alright, thanks for the research, i'll look into solving it asap

**Comment by CodedSakura** [comment]
fixed in BlossomLib v2.4.1
