### ISSUE TITLE
I'm getting a crash, I'm not sure which mod is causing it.

### ISSUE THREAD

**Issue by stantios** [BlossomMods/BlossomWarps#5]
Description: My server keeps crashing after adding both BlossomWarps and BlossomLib, I'm not sure which mod is causing it since it keeps saying a different mod is causing the crash each time. First it said, it was Banhammer so I removed that next it said the Vanish mod is causing the crash so I removed that and now it's just crashing out of nowhere.

Log: https://mclo.gs/5ktz7Uk

**Comment by CodedSakura** [comment]
`floodgate` adding `adventure-platform-fabric` is my suspicion, as APF has caused crashes with my mods in the past. if removing `floodgate` does fix it, please report back!

**Comment by stantios** [comment]
I can say that removing that mod did fix the crash.

**Comment by CodedSakura** [comment]
fyi, i'm keeping the issue open until i know *why* it APF crashes with my mods

**Comment by stantios** [comment]
Ok, that's fine

**Comment by CodedSakura** [comment]
i asked the devs of adventure and now know how to fix it, so am closing this issue / moving it to https://github.com/BlossomMods/BlossomLib/issues/5
