### ISSUE TITLE
Blossom Warps not working at all. (Incorrect argument for command at position 6) : warps

### ISSUE THREAD

**Issue by GoTaco** [BlossomMods/BlossomWarps#8]
/warps just not working at all on my server. and even in a isolated environment with just it its not working current lib and warps mod for 1.20.1 

![image](https://github.com/BlossomMods/BlossomWarps/assets/27034596/91e1785a-85e8-4b5a-ab7c-1637d6178cad)

**Comment by CodedSakura** [comment]
that is very odd, did you manage to fix this issue?

**Comment by CodedSakura** [comment]
> [!WARNING]  
> due to inactivity i'm scheduling this issue for closure on 2024-06-28, unless anyone else has encountered this and can report, or the original author can provide more details
