### ISSUE TITLE
/warp <warp> <who> works with permission level 0

### ISSUE THREAD

**Issue by SirDoomTurtle** [BlossomMods/BlossomWarps#9]
I wanted to add this mod to my server for a simple spawn warp, but quickly found out that all players, even the ones with permission level 0, can warp other players with this command.

In the mod description, it says the default permission level for /warp <warp> <who> should be 2.

**Comment by CodedSakura** [comment]
are you using LuckPerms or similar?

**Comment by SirDoomTurtle** [comment]
I am using the "player roles" mod to manage permissions on my server. I specifically allow the /warp command using the following syntax in that mod's config: "warp": "allow".

I have a feeling that this is actually the reason why the permissions for the arguments don't work. I will troublshoot this further and get back to this thread once I find that out.

**Comment by CodedSakura** [comment]
yeah, that is likely. a similar issue occurs if you give the `blossom.warps.warp` permission using luckperms. i suggest leaving the permissions alone (unless somehow Player Roles takes away the ability to use the `/warp` command entirely)

**Comment by SirDoomTurtle** [comment]
Yes unfortunately, the way it works is that I have to deny all commands for the base player role, and then allow specific commands for example "warp" : "allow".
I think this then allows the warp command with any arguments and overrides the default permissions of blossom. (because I assume palyer roles uses RegEx for command parsing).

I think I might have to switch to LuckyPerms so I don't have to change the default blossom permissions to fix this issue.
